package de.kp.shopify.insight.model
/* Copyright (c) 2014 Dr. Krusche & Partner PartG
* 
* This file is part of the Shopify-Insight project
* (https://github.com/skrusche63/shopify-insight).
* 
* Shopify-Insight is free software: you can redistribute it and/or modify it under the
* terms of the GNU General Public License as published by the Free Software
* Foundation, either version 3 of the License, or (at your option) any later
* version.
* 
* Shopify-Insight is distributed in the hope that it will be useful, but WITHOUT ANY
* WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
* A PARTICULAR PURPOSE. See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with
* Shopify-Insight. 
* 
* If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * TODO: Integrate Jollydays project and defines calendars
 * for holidays 
 */

/**
 * ParquetDOW is a data structure that specifies the 
 * customer-specific day of week support and preference; 
 * itcan be used, to e.g. determine which of the customer 
 * is a typical weekend buyer.
 * 
 * This information contributes to the temporal dimension
 * of the customer.
 */
case class ParquetDOW(
  site:String,
  user:String,
  
  day:Int,
  
  supp:Double,
  pref:Double,
  
  total:Int
)
/**
 * ParquetFRP is a data structure that specifies the
 * customer-specific purchase frequency in terms of 
 * days in between two subsequent purchase transactions.
 * 
 * This information contributes to the temporal dimension 
 * of the customer.
 */
case class ParquetFRP(
  site:String,
  user:String,
  /*
   * This profile holds the timestamp of the last purchase 
   * of the customer; this field is used to determine, whether 
   * he or she gets cold
   */
  recency:Long,
  timespan:Int,
  
  avg_timespan:Double,
  min_timespan:Int,
  max_timespan:Int,
  
  supp:Double,
  pref:Double,
  
  total:Int
)
/**
 * ParquetHOD is a data structure that specifies the
 * customer specific hour of the day support and preferences.
 * 
 * This information contributes to the temporal dimension 
 * of the customer.
 */
case class ParquetHOD(
  site:String,
  user:String,
  
  hour:Int,
  
  supp:Double,
  pref:Double,
  
  total:Int
)

case class ParquetITP(
  site:String,
  user:String,
  
  item:Int,
  
  supp:Int,
  pref:Double,
  
  total:Int
)
/**
 * ParquetRFM is a data structure that specifies an e-commerce
 * RFM table, extended by the quantiles for the respective RFM
 * attributes.
 * 
 * Quantiles are used later on to segment customers due to their
 * respective RFM attributes.  
 */
case class ParquetRFM(
  site:String,
  user:String,

  today:Long,
  
  R:Int,
  R_quantiles:String,
  
  F:Int,
  F_quantiles:String,
  
  M:Float,
  M_Quantiles:String
)

/**
 * ParquetASR is a data structure that is shared with Predictiveworks'
 * Association Analysis engine; it is generated by the ASRPreparer and
 * used by the Association Rule Mining algorithm
 */
case class ParquetASR(site:String,user:String,group:String,item:Int)
/**
 * ParquetSTM is a data structure that is shared with Predictiveworks'
 * Intent Recognition engine; it is generated by the STMPreparer and 
 * used by the Markov and Hidden Markov algorithm
 */
case class ParquetSTM(
  site:String,
  user:String,
  
  amount:Float,
  timestamp:Long,
  
  state:String
) 
